### PR TITLE
Base implementation of pilot.info (Information Component)

### PR DESCRIPTION
**Pull request by anisyonk**
Small description about implemented architecture:

The main `InformationService` (infoservice.py) aggregates data coming from various Info Providers, overwrites them according to specified priorities and providers (internal) high level API to resolve data, hosts and exposes cached instances of high level Data containers (like QueueData, StorageData, SiteData etc).

For the moment, 3 info providers implemented:
  - `PilotConfigProvider` (configinfo.py) - which is used to extract/customize settings specific for given Pilot instance
  - `JobInfoProvider` (jobinfo.py) - which is used to extract settings/customize specific for given Job
  - `ExtInfoProvider`(extinfo.py)  - used to retrieve data from external source(s) (AGIS, PanDA, etc..)

Current priority of providers is `configinfo` (highest priority), `jobinfo`, `extinfo` (default). It means that the settings defined in PilotConfig and exposed via `PilotConfigProvider` will overwrite everything. 

It's up to `ExtInfoProvider` logic to merge data and organize proper priority of external sources being used, it could be done individually for each query.

Full `QueueData` at the level of  `ExtInfoProvider` is constructed from 2 blocks:
  1. the first is considered as a master data providing minimum information (mainly PanDA oriented to let the panda server centrally overwrite or extend something, e.g. without structured/heavy data like `copytools`) -- current fail-over order for such source is `['LOCAL', 'PANDA', 'CVMFS', 'AGIS']`
 2. the 2nd block used as default include the full (extendent) list of schedconfig attributes from AGIS/CVMFS or whatever-- (default fail-over order is `['LOCAL', 'CVMFS', 'AGIS', 'PANDA']`)

The priority which used to load second block of queuedata can be configured/overwritten by `confinfo` or `jobinfo` (`resolve_schedconf_sources` function).

The instance of `InformationService` is constructed globally (ala singleton) and initialized once Pilot starts.
Such singleton instance is available in `pilot.info`,

typical example to resolve Job independent settings via Information Service:
```
from pilot.info import infosys
_maxinputsize = infosys.queuedata.maxwdir
```
Once pilot get a job, another job specific instance of `InformationService` is created and attached to the Job structure.

Typical example, to resolve queuedata from Job specific infosys:

```
 \# job is a job structure/dict passed to the function (from `queues`)
 container_name = job['infosys'].queuedata.container_type.get("pilot")  # resolve container name for user=pilot
```

*Notes and proposal about Job class:*

Currently,  Job data is just a `dict`, but actually like other similar Data structure (QueueData, StorageData,..) it could be easily unified and extended from `BaseData` class (lightweight object based implementation) which supports schema translation (between Pilot internal one and ext sources), built-in casting to proper python type,  validation of  each individual field and more..

regards,
Alexey

### CODE REVIEW

**Comment by PalNilsson** [comment]
Great, thanks Alexey. The flake8 errors are mainly the errors we decided to ignore. You can add the line "ignore = E262,E265,E266" to your .flake8 file and commit it. My own pull request can be done later.

**Comment by anisyonk** [comment]
Paul, indeed I was added it before applying the push request: https://github.com/PanDAWMS/pilot2/pull/42/commits/a25f84cc178d9a28417c4b74dcb0afed0ea1d7eb

but it looks like that the updates of flake8 config within a pull request is not considered to validate the same request..

Could you push updated  .flake8 to the next and I will rebase.

However there is one more error coming from "pep8-naming" - the N804, which requires "self" variable to be named as "cls":) for the class method.... mmm who enforced to follow such rules?))

`pilot/info/dataloader.py:42:9: N804 first argument of a classmethod should be named 'cls'`

 personally I don't like such restriction in a coding style because from my point of view it's kind useless cosmetic (the proper decorator should clarify if a method static or not..  moreover a meta class could completely overwrite a function behavior, plus if for whatever reasons someone removes the decorator you have to patch the body of a function.. redundant actions which confuses developers who believes that "cls" means the classmethod:) ).
 So Paul, if you fill the same and could just add the "N804" into the ignore list that would be fine. I can also apply the patch for follow N804 rule otherwise .. but better to ignore such cosmetic:) thanks.

**Comment by PalNilsson** [comment]
Turned out that the .flake8 file where I added the updated ignore list is for Windows systems.. I added .config/flake8 which is for linux systems. Please try to rebase now. I will remove the .flake8 file later.

**Comment by PalNilsson** [comment]
Probably the .flake8/.config/flake8 files are not used by Travis but only for local testing. There is a config file for the Travis test but I haven't been able to locate it yet. It can be browsed only, not edited. I'm searching for it in the Travis web pages.

**Comment by PalNilsson** [comment]
Ok found it. Wait..

**Comment by anisyonk** [comment]
I think we need to pass config file explicitly via `flake8 --config` option.. as I see from the docs the default location is at the HOME (`~`) dir as the doc states:

Note that Flake8 looks for `~\.flake8` on Windows and `~/.config/flake8` on Linux and other Unix systems.

**Comment by PalNilsson** [comment]
Maybe the same yes. Updating the travis config file worked in my latest full request, so you can try again..

**Comment by PalNilsson** [comment]
Try to add --ignore <errors> like I did in my latest pull request. The VM is running linux I believe so possibly .flake8 is ignored.

**Comment by anisyonk** [comment]
it failed with --ignore too.  check one line above

https://travis-ci.org/PanDAWMS/pilot2/builds/342290813?utm_source=github_status&utm_medium=notification

**Comment by anisyonk** [comment]
Paul, finally I got these things done. 

I upgraded travis settings to consider different `flake8` config for py2.6 & py2.7.

The problem with flake8 for python2.6 comes from the fact  that it does not support both `ignore` and `select` options, so I removed explicit declaration of `select` items (so that the flake default settings are used - which do not cover all the error types). 

I considered python2.7 as default python version for Pilot which include all the flake errors and relies on (default) `.flake8` config file in Pilot.

**Comment by PalNilsson** [comment]
Great, thanks a lot!

**Pull request merged**
