### PR TITLE
resolve_replicas and direct access updates

### PR DESCRIPTION
**Pull request by anisyonk**
**Updates:**
- resolve_replicas() logic updated to consider protocol priories exposed by Rucio
- resolve_replica fix to consider first direct access compatible protocols

**Notes:**
Direct access look up logic: if a PQ has several DDMs associated and direct access mode requested for input, then direct read will be used only if direct access compatible replica is stored at 1st DDMEndpoint, otherwise copy to scratch will be applied. Is it OK in terms of expected behavior?

Paul, can you please run test jobs for direct_access checks. thanks. I have not tested with real jobs this part.

### CODE REVIEW

**Comment by PalNilsson** [comment]
Thanks Alexey. Please check this job: https://bigpanda.cern.ch/job?pandaid=4077257171&timestamp=12:29:32

**Comment by anisyonk** [comment]
Paul, thanks,

this job run with pilot which does not include updates from this MR.

**Comment by PalNilsson** [comment]
Hi, there's an issue with a squid that is not updating the tarball - I ran a second job where I modified the build number, but it still took the old version. Will try again later. /P

**Comment by PalNilsson** [comment]
Please check this one: https://bigpanda.cern.ch/job?pandaid=4078527269

**Comment by anisyonk** [comment]
so, it worked as expected, since there is no ROOT protocols associated with input DDM UTA_SWT2_DATADISK and direct access over WAN is allowed Pilot resolve fist available root replica from GOEGRID_DATADISK.

Paul, can you add to the UTA_SWT2_DATADISK http://atlas-agis.cern.ch/agis/service/detail/18042/ any root protocol and make it being lowest priority .. so that we can check if pilot properly filter root protocols.

**Comment by anisyonk** [comment]
Paul, again both jobs run by outdated Pilot,

for what concern (direct access LAN false, WAN true),

previously I assumed that if WAN is enabled then whenever is possible LAN could be used as well,

wrong assumption?

**Comment by PalNilsson** [comment]
But I downloaded the zip from your github and updated the version to
http://aipanda067.cern.ch/pilots/2018-10-01/CERN-PROD_UCORE-14817-pilot2/5537648.0.out|Condor|PR|2.0.0 (81AA)

**Comment by anisyonk** [comment]
maybe something went wrong, 
 because there should not be the line `allowremoteinputsallowremoteinputs` in the output since I fixed this 

2018-10-01 08:00:26,872 | INFO     | copytool_in         | pilot.util.auxiliary             | resolve_replicas          | Number of resolved replicas:
lfn=HITS.06828093._000096.pool.root.1: replicas=4, allowremoteinputsallowremoteinputs=True, is_directaccess=True


https://github.com/PanDAWMS/pilot2/pull/100/files#diff-04265d080c2dd5ec45a3a8b17bfb8aacL217

**Comment by PalNilsson** [comment]
Hi. Please prepare a tarball with the version you want tested, update the build number in pilot.py. Put the tarball in a www directory where I can curl it from. Cheers, P

**Comment by PalNilsson** [comment]
Ok, check these ones
https://bigpanda.cern.ch/job?pandaid=4081628982&timestamp=14:17:34
https://bigpanda.cern.ch/job?pandaid=4081629523&timestamp=14:17:42

**Comment by anisyonk** [comment]
looks OK.
however root:// for CERN-PROD_DATADISK is already configured as primary protocol so that it does not confirm if root protocol look up in case of direct access applied as expected , in any case I think it should work since the logic is ported from Pilot1. in any case it can be turned later if need.

**Pull request merged**
