### PR TITLE
cp and ln features added

### PR DESCRIPTION
**Pull request by pavlo-svirin**
I've also run flake8 tests, worked fine

### CODE REVIEW

**Comment by complynx** [comment]
@pavlo-svirin, use these lines to install necessary flake8 plugins.

pip install 'unittest2'
pip install 'flake8<3.0.0'
pip install 'pep8-naming'
pip install 'flake8-blind-except'
pip install 'pycodestyle'
flake8 pilot.py pilot/
unit2 -v

**Comment by PalNilsson** [comment]
Hi, was this closed by mistake? (I will be on vacation from tomorrow but will check mail every now and then during Christmas)

**Comment by complynx** [comment]
Looks like Pavlo closed it by himself. Maybe he'll fix it and then reopen.

**Comment by pavlo-svirin** [comment]
Travis showed me one more error (N806: function variables must be lowercase) which was ignored by my local flake8. Will test again and reopen.

**Pull request closed without merging**
