### PR TITLE
Input file (direct) access workflow upgraded (over LAN & WAN)

### PR DESCRIPTION
**Pull request by anisyonk**
Data API and top workflow updates:
 
- direct access workflow upgraded (support `allow_lan` & `allow_wan`,  `direct_access_lan` & `direct_access_wan`)
 - removed direct access handling from copytools (gfal, lsm, rucio, xrdcp), the logic is applied at top level.
- stage-in: ignore already processed files on stage-in retry with failover copytool
-  Other minor updates (fix  `clean_boolean` validation to use default value if no input passed or `None` passed)

Tested against production and pilot test jobs.

**Affected (direct) access settings**:

`Job` settings requested by server: `transfertype=direct` (per job)  for remoteio, `storage_token=local` (per specific file) for copy2scratch 
`Job` input options: `--accessmode=direct` for remoteio,  `--accessmode=copy` or `--useLocalIO` for copy2scratch
`PandaQueue` settings: `allow_lan` + `direct_acccess_lan` for remoteio over `LAN`, `allow_wan` +  `direct_access_wan` for remoteio over `WAN`

**Logic**

1. By default access method is **copyt2scrach**.
2. Each input file with `transfertype = 'direct'` and `storage_token!=local` as requested by PanDA could potentially use remotio (direct access)

3. Job input options (`--accessmode`, `--useLocalIO`) overwrite PanDA server decision.

4. PandaQueue configuration takes finally controls either LAN/WAN replica can be used and direct access method could be applied for given file, pilot takes PanDA server decision and Job input options and apply for them PandaQueue settings:
  - for LAN: requires: allow_lan=True + direct_access_lan=True + and availability of appropriate replica for remote io
  - for WAN: requires: allow_wan=True + direct_access_wan=True + and availability of appropriate replica for remote io

Alexey

### CODE REVIEW

**Comment by anisyonk** [comment]
Paul, can you please run it with direct access enabled jobs?
 (in principle, HC could overwrite via jobparams `--accessmode` to use remoteio if task forbids it)

`allow_wan` is disabled by default,

For Ilija's case (VP jobs), we can overwrite queuedata.allow_wan=True via HC params using `--overwriteQueueData "{'allow_wan': True}"`

thanks

**Comment by PalNilsson** [comment]
Hi. I've updated the RC test version. Check the jobs from this page: https://bigpanda.cern.ch/errors/?prodsourcelabel=rc_test2 the jobs should start using this version soon (v 2.2.1 (6)). Please sync the code to the latest version (git fetch upstream; git merge upstream/next). I will go to CHEP next week so I don't really want to release new code until after. But if we conclude that everything is working properly by Monday we could release it then.

**Comment by davidgcameron** [comment]
Please check this job: https://bigpanda.cern.ch/job?pandaid=4521703184
The pilot should use the copy on disk with storm:// protocol but instead tries the tape copy.

**Comment by anisyonk** [comment]
David,

Pilot follows replica priorities returned by Rucio,

INFN-T1_MCTAPE is in accepted inputddm list for ANALY_INFN-T1,

according to Rucio most preferred replica returned by list_replicas() (with highest priority=1) is srm at INFN-T1_MCTAPE, what Pilot should do in this case ? :)


https://bigpanda.cern.ch//media/filebrowser/a65f63f1-d86a-4d9e-8b91-50a8092c5cfd/user.gangarbt/tarball_PandaJob_4521703184_ANALY_INFN-T1/pilotlog.txt

u'srm://storm-fe.cr.cnaf.infn.it:8444/srm/managerv2?SFN=/atlas/atlasmctape/mc15_13TeV/AOD/e3869_s2608_s2183_r6630_r6264/mc15_13TeV.423202.Pythia8B_A14_CTEQ6L1_Jpsie3e13.merge.AOD.e3869_s2608_s2183_r6630_r6264_tid05536542_00/AOD.05536542._000001.pool.root.1': {u'domain': u'lan', u'rse': u'INFN-T1_MCTAPE', **u'priority': 1,** u'rse_id': u'7a4a426bc9c446988af74822fd6d7f5c', u'volatile': False, u'client_extract': False, u'type': u'TAPE'},


Do we need to filter replicas by type (DISK,TAPE)?

**Comment by anisyonk** [comment]
OK, I've  implemented following updates:
 - consider only `DISK` replicas from rucio
 - keep priority of `LAN` replicas according to `inputddms` (`PandaQueue.astorages` list)

Paul, please update RC test pilot with these fixes. thanks

**Comment by PalNilsson** [comment]
Thanks. RC pilot updated.

**Comment by anisyonk** [comment]
Fixed stage-in logic to ignore already processed files on transfer retry with different copytool

**Comment by PalNilsson** [comment]
Thanks. Did you confirm that direct access works as expected? I so, would like to approve this during the day and merge it with my latest changes so we can release on Monday.

**Comment by PalNilsson** [comment]
Shouldn't this have used direct access?
https://bigpanda.cern.ch/job?pandaid=4523345593

**Comment by anisyonk** [comment]
`transferType` is empty/NULL, so that it use copy to scratch

**Comment by anisyonk** [comment]
it looks that we don't have HC jobs requesting direct access for `rc_test2`

**Comment by PalNilsson** [comment]
We only used transferType for production jobs in the past. It was ignored for user jobs

**Comment by anisyonk** [comment]
OK, so that the logic (Panda server preference for remoteio) should be following:

for prod job: direct access should be used if `transferType=direct` and `prodDBlockToken!=local`
for analy job: direct access should be used if `prodDBlockToken!=local`

is it correct?

**Comment by PalNilsson** [comment]
Right, thanks. I'm updating the RC version.

**Comment by anisyonk** [comment]
last bit, for build jobs,  we need also exclude them from using direct access, right?

**Comment by PalNilsson** [comment]
Yes

**Comment by anisyonk** [comment]
or it's not critical and build job is not affected since it does not take any root:// files for input?

**Comment by PalNilsson** [comment]
I think we used to an explicit if statement that prevented it

**Comment by anisyonk** [comment]
I checked `buildGen-00-00-01` and `buildJob-00-00-03` jobs, they do not take any input at all,
I think it should work, lets check, in case of issues I will explicitly exclude `remoteio` for build jobs.

Currently a preferred decision to use remoteio is applied at the step of `infiles` initialization, while to identify either it's a build job or not we could only by checking `outfiles`. so to avoid overcomplication lets ignore given extra check:)

**Comment by PalNilsson** [comment]
Now the jobs fail at CERN:
https://bigpanda.cern.ch/job?pandaid=4523514379
Can you check?

**Comment by anisyonk** [comment]
Paul, now it should work,
please update RC test pilot. thanks

**Comment by PalNilsson** [comment]
Ok done on Sunday morning, new version is 2.2.1 (1AA3). I will merge it later on Sunday with my version

**Pull request merged**
