### PR TITLE
Changed gs.py for GCS buckets with automatic bucket name extraction

### PR DESCRIPTION
**Pull request by yesw2000**
Hi Paul,

I modified the plugin gs.py, and tested it successfully. Please help integrate into the master branch.

Thanks,

Shuwei

### CODE REVIEW

**Comment by PalNilsson** [comment]
Hi,

Thanks. There are a few things that flake8 will complain about, so you need to address those (e.g. double empty lines inside functions and variable names like someName [should be some_name]). Easiest is you simply run flake8 manually and then commit the changes. 

Then there are assumptions about the output files, that I mentioned before, that are unique to you so it's not suitable for anyone else. In the copy_out() function you are uploading all files in the workdir except gz file to the object store (even if that is fine for the moment, it't not good if you end up with a lot of files all of a sudden in the workdir). Can you simply add the files you want ("pilotlog.txt", "payload.stdout", "payload.stderr") to the normal output file list when you define the job? That's how it should be done. The copy_out() should then loop over the job.outdata list (a list of FileSpec objects) and transfer them one by one.

Cheers, 
Paul

**Comment by yesw2000** [comment]
Hi Paul,

OK. I can run a flake8 check.

Yes, I am not very happy with the assumption about the log filenames. If my understanding is correct, the output file list provided panda job submissions, are normally generated by user jobs. But the log filenames of pilot jobs and payload jobs are configured in pilot, not by the user jobs. I am thinking about specifying the value parameter of taskParamMap['log'] with ‘ ‘ (a space) or ‘/’, to trigger pilot skip the tgz creation of log files, and to tell the copytool plugin, to transfer all the files under that PFN directory. It is still not so perfect, but makes more sense.

Best,

--Shuwei

**Comment by yesw2000** [comment]
Hi @PalNilsson ,

Following your suggestion, I corrected the text format in **gs.py**, and it **passed the flake8 check locally**.

Please help integrate into the official pilot.

Best,

Shuwei

**Comment by PalNilsson** [comment]
Hi,
There are still flake8 complaint, please see the details on this page.
Cheers, Paul

**Comment by yesw2000** [comment]
Hi Paul,

I just lower cased 2 variable names: reObj and url_pilotLog. Hoping that it has complied with the flake8 requirement.

Shuwei

**Comment by PalNilsson** [comment]
Thanks, merged

**Pull request merged**
