### PR TITLE
always resolve real source in mv methods

### PR DESCRIPTION
**Pull request by davidgcameron**

### CODE REVIEW

**Comment by PalNilsson** [comment]
Hi David, does this resolve a problem you are having? I am planning on releasing the next version later today so please let me know if it is urgent and I will update the RC pilot one last time.

**Comment by davidgcameron** [comment]
Rod confirmed it's not urgent so no need to release today.

**Comment by PalNilsson** [comment]
Thanks David. It will go in with the next release then. Not before CHEP unless there's some emergency, in which case I will sneak in this as well..

**Comment by PalNilsson** [comment]
I'm approving this as the dev pilot is anyway delayed and will not be released until beginning of November

**Pull request merged**
